{
    "patcher": {
        "fileversion": 1,
        "appversion": { "major": 9, "minor": 1, "revision": 2, "architecture": "x64", "modernui": 1 },
        "classnamespace": "box",
        "rect": [ 800.0, 100.0, 820.0, 920.0 ],
        "boxes": [
            { "box": { "id": "obj-10", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 10.0, 160.0, 22.0 ], "text": "-- SPEED --" } },
            { "box": { "id": "obj-80", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 34.0, 130.0, 22.0 ], "text": "speed_kmh" } },
            { "box": { "id": "obj-20", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 34.0, 130.0, 22.0 ], "text": "r speed_kmh" } },
            { "box": { "id": "obj-50", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 34.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-81", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 58.0, 130.0, 22.0 ], "text": "speed_mph" } },
            { "box": { "id": "obj-21", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 58.0, 130.0, 22.0 ], "text": "r speed_mph" } },
            { "box": { "id": "obj-51", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 58.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-82", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 82.0, 130.0, 22.0 ], "text": "speed_ms" } },
            { "box": { "id": "obj-22", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 82.0, 130.0, 22.0 ], "text": "r speed_ms" } },
            { "box": { "id": "obj-52", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 82.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-11", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 114.0, 160.0, 22.0 ], "text": "-- FLAGS --" } },
            { "box": { "id": "obj-83", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 138.0, 130.0, 22.0 ], "text": "abs_enabled" } },
            { "box": { "id": "obj-23", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 138.0, 130.0, 22.0 ], "text": "r abs_enabled" } },
            { "box": { "id": "obj-53", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 138.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-84", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 162.0, 130.0, 22.0 ], "text": "abs_in_action" } },
            { "box": { "id": "obj-24", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 162.0, 130.0, 22.0 ], "text": "r abs_in_action" } },
            { "box": { "id": "obj-54", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 162.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-85", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 186.0, 130.0, 22.0 ], "text": "tc_in_action" } },
            { "box": { "id": "obj-25", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 186.0, 130.0, 22.0 ], "text": "r tc_in_action" } },
            { "box": { "id": "obj-55", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 186.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-86", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 210.0, 130.0, 22.0 ], "text": "tc_enabled" } },
            { "box": { "id": "obj-26", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 210.0, 130.0, 22.0 ], "text": "r tc_enabled" } },
            { "box": { "id": "obj-56", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 210.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-87", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 234.0, 130.0, 22.0 ], "text": "in_pit" } },
            { "box": { "id": "obj-27", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 234.0, 130.0, 22.0 ], "text": "r in_pit" } },
            { "box": { "id": "obj-57", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 234.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-88", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 258.0, 130.0, 22.0 ], "text": "engine_limiter" } },
            { "box": { "id": "obj-28", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 258.0, 130.0, 22.0 ], "text": "r engine_limiter" } },
            { "box": { "id": "obj-58", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 258.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-12", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 290.0, 160.0, 22.0 ], "text": "-- G-FORCE (G) --" } },
            { "box": { "id": "obj-89", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 314.0, 130.0, 22.0 ], "text": "accG_vertical" } },
            { "box": { "id": "obj-29", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 314.0, 130.0, 22.0 ], "text": "r accG_vertical" } },
            { "box": { "id": "obj-59", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 314.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-90", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 338.0, 130.0, 22.0 ], "text": "accG_horizontal" } },
            { "box": { "id": "obj-30", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 338.0, 130.0, 22.0 ], "text": "r accG_horizontal" } },
            { "box": { "id": "obj-60", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 338.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-91", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 362.0, 130.0, 22.0 ], "text": "accG_frontal" } },
            { "box": { "id": "obj-31", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 362.0, 130.0, 22.0 ], "text": "r accG_frontal" } },
            { "box": { "id": "obj-61", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 362.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-13", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 394.0, 160.0, 22.0 ], "text": "-- LAP --" } },
            { "box": { "id": "obj-92", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 418.0, 130.0, 22.0 ], "text": "lap_time (ms)" } },
            { "box": { "id": "obj-32", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 418.0, 130.0, 22.0 ], "text": "r lap_time" } },
            { "box": { "id": "obj-62", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 418.0, 80.0, 22.0 ] } },
            { "box": { "id": "obj-93", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 442.0, 130.0, 22.0 ], "text": "last_lap (ms)" } },
            { "box": { "id": "obj-33", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 442.0, 130.0, 22.0 ], "text": "r last_lap" } },
            { "box": { "id": "obj-63", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 442.0, 80.0, 22.0 ] } },
            { "box": { "id": "obj-94", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 466.0, 130.0, 22.0 ], "text": "best_lap (ms)" } },
            { "box": { "id": "obj-34", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 466.0, 130.0, 22.0 ], "text": "r best_lap" } },
            { "box": { "id": "obj-64", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 466.0, 80.0, 22.0 ] } },
            { "box": { "id": "obj-95", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 490.0, 130.0, 22.0 ], "text": "lap_count" } },
            { "box": { "id": "obj-35", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 490.0, 130.0, 22.0 ], "text": "r lap_count" } },
            { "box": { "id": "obj-65", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 490.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-14", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 522.0, 160.0, 22.0 ], "text": "-- CONTROLS --" } },
            { "box": { "id": "obj-96", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 546.0, 130.0, 22.0 ], "text": "gas" } },
            { "box": { "id": "obj-36", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 546.0, 130.0, 22.0 ], "text": "r gas" } },
            { "box": { "id": "obj-66", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 546.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-97", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 570.0, 130.0, 22.0 ], "text": "brake" } },
            { "box": { "id": "obj-37", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 570.0, 130.0, 22.0 ], "text": "r brake" } },
            { "box": { "id": "obj-67", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 570.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-98", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 594.0, 130.0, 22.0 ], "text": "clutch" } },
            { "box": { "id": "obj-38", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 594.0, 130.0, 22.0 ], "text": "r clutch" } },
            { "box": { "id": "obj-68", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 594.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-99", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 618.0, 130.0, 22.0 ], "text": "engine_rpm" } },
            { "box": { "id": "obj-39", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 618.0, 130.0, 22.0 ], "text": "r engine_rpm" } },
            { "box": { "id": "obj-69", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 618.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-100", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 642.0, 130.0, 22.0 ], "text": "steer" } },
            { "box": { "id": "obj-40", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 642.0, 130.0, 22.0 ], "text": "r steer" } },
            { "box": { "id": "obj-70", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 642.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-101", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 666.0, 130.0, 22.0 ], "text": "gear" } },
            { "box": { "id": "obj-41", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 666.0, 130.0, 22.0 ], "text": "r gear" } },
            { "box": { "id": "obj-71", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 666.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-102", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 690.0, 130.0, 22.0 ], "text": "cg_height" } },
            { "box": { "id": "obj-42", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 690.0, 130.0, 22.0 ], "text": "r cg_height" } },
            { "box": { "id": "obj-72", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 690.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-15", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 722.0, 160.0, 22.0 ], "text": "-- POSITION --" } },
            { "box": { "id": "obj-103", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 746.0, 130.0, 22.0 ], "text": "car_pos_normalized" } },
            { "box": { "id": "obj-43", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 746.0, 130.0, 22.0 ], "text": "r car_pos_normalized" } },
            { "box": { "id": "obj-73", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 746.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-104", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 770.0, 130.0, 22.0 ], "text": "car_slope" } },
            { "box": { "id": "obj-44", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 770.0, 130.0, 22.0 ], "text": "r car_slope" } },
            { "box": { "id": "obj-74", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 770.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-105", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 794.0, 130.0, 22.0 ], "text": "car_x" } },
            { "box": { "id": "obj-45", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 794.0, 130.0, 22.0 ], "text": "r car_x" } },
            { "box": { "id": "obj-75", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 794.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-106", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 818.0, 130.0, 22.0 ], "text": "car_y" } },
            { "box": { "id": "obj-46", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 818.0, 130.0, 22.0 ], "text": "r car_y" } },
            { "box": { "id": "obj-76", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 818.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-107", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 10.0, 842.0, 130.0, 22.0 ], "text": "car_z" } },
            { "box": { "id": "obj-47", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 145.0, 842.0, 130.0, 22.0 ], "text": "r car_z" } },
            { "box": { "id": "obj-77", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 280.0, 842.0, 70.0, 22.0 ] } },
            { "box": { "id": "obj-200", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 10.0, 420.0, 22.0 ], "text": "-- WHEEL DATA (FL / FR / RL / RR) --" } },
            { "box": { "id": "obj-201", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 530.0, 34.0, 50.0, 22.0 ], "text": "FL" } },
            { "box": { "id": "obj-202", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 600.0, 34.0, 50.0, 22.0 ], "text": "FR" } },
            { "box": { "id": "obj-203", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 670.0, 34.0, 50.0, 22.0 ], "text": "RL" } },
            { "box": { "id": "obj-204", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 740.0, 34.0, 50.0, 22.0 ], "text": "RR" } },
            { "box": { "id": "obj-210", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 58.0, 145.0, 22.0 ], "text": "wheel_speed" } },
            { "box": { "id": "obj-230", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 58.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-244", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 58.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-258", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 58.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-272", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 58.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-211", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 82.0, 145.0, 22.0 ], "text": "slip_angle" } },
            { "box": { "id": "obj-231", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 82.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-245", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 82.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-259", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 82.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-273", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 82.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-212", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 106.0, 145.0, 22.0 ], "text": "slip_angle_cp" } },
            { "box": { "id": "obj-232", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 106.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-246", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 106.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-260", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 106.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-274", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 106.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-213", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 130.0, 145.0, 22.0 ], "text": "slip_ratio" } },
            { "box": { "id": "obj-233", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 130.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-247", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 130.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-261", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 130.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-275", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 130.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-214", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 154.0, 145.0, 22.0 ], "text": "tyre_slip" } },
            { "box": { "id": "obj-234", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 154.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-248", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 154.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-262", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 154.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-276", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 154.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-215", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 178.0, 145.0, 22.0 ], "text": "nd_slip" } },
            { "box": { "id": "obj-235", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 178.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-249", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 178.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-263", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 178.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-277", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 178.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-216", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 202.0, 145.0, 22.0 ], "text": "load" } },
            { "box": { "id": "obj-236", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 202.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-250", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 202.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-264", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 202.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-278", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 202.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-217", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 226.0, 145.0, 22.0 ], "text": "dy (lat.force)" } },
            { "box": { "id": "obj-237", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 226.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-251", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 226.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-265", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 226.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-279", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 226.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-218", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 250.0, 145.0, 22.0 ], "text": "mz (align.trq)" } },
            { "box": { "id": "obj-238", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 250.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-252", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 250.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-266", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 250.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-280", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 250.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-219", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 274.0, 145.0, 22.0 ], "text": "tyre_dirty" } },
            { "box": { "id": "obj-239", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 274.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-253", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 274.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-267", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 274.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-281", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 274.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-220", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 298.0, 145.0, 22.0 ], "text": "camber (rad)" } },
            { "box": { "id": "obj-240", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 298.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-254", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 298.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-268", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 298.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-282", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 298.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-221", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 322.0, 145.0, 22.0 ], "text": "tyre_radius" } },
            { "box": { "id": "obj-241", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 322.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-255", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 322.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-269", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 322.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-283", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 322.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-222", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 346.0, 145.0, 22.0 ], "text": "tyre_loaded_radius" } },
            { "box": { "id": "obj-242", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 346.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-256", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 346.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-270", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 346.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-284", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 346.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-223", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 380.0, 370.0, 145.0, 22.0 ], "text": "suspension_height" } },
            { "box": { "id": "obj-243", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 530.0, 370.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-257", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 600.0, 370.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-271", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 670.0, 370.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-285", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 740.0, 370.0, 65.0, 22.0 ] } },
            { "box": { "id": "obj-300", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 420.0, 160.0, 22.0 ], "text": "r wheel_speed_fl" } },
            { "box": { "id": "obj-301", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 444.0, 160.0, 22.0 ], "text": "r slip_angle_fl" } },
            { "box": { "id": "obj-302", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 468.0, 160.0, 22.0 ], "text": "r slip_angle_cp_fl" } },
            { "box": { "id": "obj-303", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 492.0, 160.0, 22.0 ], "text": "r slip_ratio_fl" } },
            { "box": { "id": "obj-304", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 516.0, 160.0, 22.0 ], "text": "r tyre_slip_fl" } },
            { "box": { "id": "obj-305", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 540.0, 160.0, 22.0 ], "text": "r nd_slip_fl" } },
            { "box": { "id": "obj-306", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 564.0, 160.0, 22.0 ], "text": "r load_fl" } },
            { "box": { "id": "obj-307", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 588.0, 160.0, 22.0 ], "text": "r dy_fl" } },
            { "box": { "id": "obj-308", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 612.0, 160.0, 22.0 ], "text": "r mz_fl" } },
            { "box": { "id": "obj-309", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 636.0, 160.0, 22.0 ], "text": "r tyre_dirty_fl" } },
            { "box": { "id": "obj-310", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 660.0, 160.0, 22.0 ], "text": "r camber_fl" } },
            { "box": { "id": "obj-311", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 684.0, 160.0, 22.0 ], "text": "r tyre_radius_fl" } },
            { "box": { "id": "obj-312", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 708.0, 160.0, 22.0 ], "text": "r tyre_loaded_radius_fl" } },
            { "box": { "id": "obj-313", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 732.0, 160.0, 22.0 ], "text": "r suspension_fl" } },
            { "box": { "id": "obj-314", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 420.0, 160.0, 22.0 ], "text": "r wheel_speed_fr" } },
            { "box": { "id": "obj-315", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 444.0, 160.0, 22.0 ], "text": "r slip_angle_fr" } },
            { "box": { "id": "obj-316", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 468.0, 160.0, 22.0 ], "text": "r slip_angle_cp_fr" } },
            { "box": { "id": "obj-317", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 492.0, 160.0, 22.0 ], "text": "r slip_ratio_fr" } },
            { "box": { "id": "obj-318", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 516.0, 160.0, 22.0 ], "text": "r tyre_slip_fr" } },
            { "box": { "id": "obj-319", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 540.0, 160.0, 22.0 ], "text": "r nd_slip_fr" } },
            { "box": { "id": "obj-320", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 564.0, 160.0, 22.0 ], "text": "r load_fr" } },
            { "box": { "id": "obj-321", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 588.0, 160.0, 22.0 ], "text": "r dy_fr" } },
            { "box": { "id": "obj-322", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 612.0, 160.0, 22.0 ], "text": "r mz_fr" } },
            { "box": { "id": "obj-323", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 636.0, 160.0, 22.0 ], "text": "r tyre_dirty_fr" } },
            { "box": { "id": "obj-324", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 660.0, 160.0, 22.0 ], "text": "r camber_fr" } },
            { "box": { "id": "obj-325", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 684.0, 160.0, 22.0 ], "text": "r tyre_radius_fr" } },
            { "box": { "id": "obj-326", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 708.0, 160.0, 22.0 ], "text": "r tyre_loaded_radius_fr" } },
            { "box": { "id": "obj-327", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 732.0, 160.0, 22.0 ], "text": "r suspension_fr" } },
            { "box": { "id": "obj-328", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 760.0, 160.0, 22.0 ], "text": "r wheel_speed_rl" } },
            { "box": { "id": "obj-329", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 784.0, 160.0, 22.0 ], "text": "r slip_angle_rl" } },
            { "box": { "id": "obj-330", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 808.0, 160.0, 22.0 ], "text": "r slip_angle_cp_rl" } },
            { "box": { "id": "obj-331", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 832.0, 160.0, 22.0 ], "text": "r slip_ratio_rl" } },
            { "box": { "id": "obj-332", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 856.0, 160.0, 22.0 ], "text": "r tyre_slip_rl" } },
            { "box": { "id": "obj-333", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 880.0, 160.0, 22.0 ], "text": "r nd_slip_rl" } },
            { "box": { "id": "obj-334", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 904.0, 160.0, 22.0 ], "text": "r load_rl" } },
            { "box": { "id": "obj-335", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 760.0, 160.0, 22.0 ], "text": "r dy_rl" } },
            { "box": { "id": "obj-336", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 784.0, 160.0, 22.0 ], "text": "r mz_rl" } },
            { "box": { "id": "obj-337", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 808.0, 160.0, 22.0 ], "text": "r tyre_dirty_rl" } },
            { "box": { "id": "obj-338", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 832.0, 160.0, 22.0 ], "text": "r camber_rl" } },
            { "box": { "id": "obj-339", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 856.0, 160.0, 22.0 ], "text": "r tyre_radius_rl" } },
            { "box": { "id": "obj-340", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 880.0, 160.0, 22.0 ], "text": "r tyre_loaded_radius_rl" } },
            { "box": { "id": "obj-341", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 904.0, 160.0, 22.0 ], "text": "r suspension_rl" } },
            { "box": { "id": "obj-342", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 928.0, 160.0, 22.0 ], "text": "r wheel_speed_rr" } },
            { "box": { "id": "obj-343", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 952.0, 160.0, 22.0 ], "text": "r slip_angle_rr" } },
            { "box": { "id": "obj-344", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 976.0, 160.0, 22.0 ], "text": "r slip_angle_cp_rr" } },
            { "box": { "id": "obj-345", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 1000.0, 160.0, 22.0 ], "text": "r slip_ratio_rr" } },
            { "box": { "id": "obj-346", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 1024.0, 160.0, 22.0 ], "text": "r tyre_slip_rr" } },
            { "box": { "id": "obj-347", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 1048.0, 160.0, 22.0 ], "text": "r nd_slip_rr" } },
            { "box": { "id": "obj-348", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 928.0, 160.0, 22.0 ], "text": "r load_rr" } },
            { "box": { "id": "obj-349", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 952.0, 160.0, 22.0 ], "text": "r dy_rr" } },
            { "box": { "id": "obj-350", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 976.0, 160.0, 22.0 ], "text": "r mz_rr" } },
            { "box": { "id": "obj-351", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 1000.0, 160.0, 22.0 ], "text": "r tyre_dirty_rr" } },
            { "box": { "id": "obj-352", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 1024.0, 160.0, 22.0 ], "text": "r camber_rr" } },
            { "box": { "id": "obj-353", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 1048.0, 160.0, 22.0 ], "text": "r tyre_radius_rr" } },
            { "box": { "id": "obj-354", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 1072.0, 180.0, 22.0 ], "text": "r tyre_loaded_radius_rr" } },
            { "box": { "id": "obj-355", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 550.0, 1072.0, 160.0, 22.0 ], "text": "r suspension_rr" } }
        ],
        "lines": [
            { "patchline": { "destination": [ "obj-50", 0 ], "source": [ "obj-20", 0 ] } },
            { "patchline": { "destination": [ "obj-51", 0 ], "source": [ "obj-21", 0 ] } },
            { "patchline": { "destination": [ "obj-52", 0 ], "source": [ "obj-22", 0 ] } },
            { "patchline": { "destination": [ "obj-53", 0 ], "source": [ "obj-23", 0 ] } },
            { "patchline": { "destination": [ "obj-54", 0 ], "source": [ "obj-24", 0 ] } },
            { "patchline": { "destination": [ "obj-55", 0 ], "source": [ "obj-25", 0 ] } },
            { "patchline": { "destination": [ "obj-56", 0 ], "source": [ "obj-26", 0 ] } },
            { "patchline": { "destination": [ "obj-57", 0 ], "source": [ "obj-27", 0 ] } },
            { "patchline": { "destination": [ "obj-58", 0 ], "source": [ "obj-28", 0 ] } },
            { "patchline": { "destination": [ "obj-59", 0 ], "source": [ "obj-29", 0 ] } },
            { "patchline": { "destination": [ "obj-60", 0 ], "source": [ "obj-30", 0 ] } },
            { "patchline": { "destination": [ "obj-61", 0 ], "source": [ "obj-31", 0 ] } },
            { "patchline": { "destination": [ "obj-62", 0 ], "source": [ "obj-32", 0 ] } },
            { "patchline": { "destination": [ "obj-63", 0 ], "source": [ "obj-33", 0 ] } },
            { "patchline": { "destination": [ "obj-64", 0 ], "source": [ "obj-34", 0 ] } },
            { "patchline": { "destination": [ "obj-65", 0 ], "source": [ "obj-35", 0 ] } },
            { "patchline": { "destination": [ "obj-66", 0 ], "source": [ "obj-36", 0 ] } },
            { "patchline": { "destination": [ "obj-67", 0 ], "source": [ "obj-37", 0 ] } },
            { "patchline": { "destination": [ "obj-68", 0 ], "source": [ "obj-38", 0 ] } },
            { "patchline": { "destination": [ "obj-69", 0 ], "source": [ "obj-39", 0 ] } },
            { "patchline": { "destination": [ "obj-70", 0 ], "source": [ "obj-40", 0 ] } },
            { "patchline": { "destination": [ "obj-71", 0 ], "source": [ "obj-41", 0 ] } },
            { "patchline": { "destination": [ "obj-72", 0 ], "source": [ "obj-42", 0 ] } },
            { "patchline": { "destination": [ "obj-73", 0 ], "source": [ "obj-43", 0 ] } },
            { "patchline": { "destination": [ "obj-74", 0 ], "source": [ "obj-44", 0 ] } },
            { "patchline": { "destination": [ "obj-75", 0 ], "source": [ "obj-45", 0 ] } },
            { "patchline": { "destination": [ "obj-76", 0 ], "source": [ "obj-46", 0 ] } },
            { "patchline": { "destination": [ "obj-77", 0 ], "source": [ "obj-47", 0 ] } },
            { "patchline": { "destination": [ "obj-230", 0 ], "source": [ "obj-300", 0 ] } },
            { "patchline": { "destination": [ "obj-231", 0 ], "source": [ "obj-301", 0 ] } },
            { "patchline": { "destination": [ "obj-232", 0 ], "source": [ "obj-302", 0 ] } },
            { "patchline": { "destination": [ "obj-233", 0 ], "source": [ "obj-303", 0 ] } },
            { "patchline": { "destination": [ "obj-234", 0 ], "source": [ "obj-304", 0 ] } },
            { "patchline": { "destination": [ "obj-235", 0 ], "source": [ "obj-305", 0 ] } },
            { "patchline": { "destination": [ "obj-236", 0 ], "source": [ "obj-306", 0 ] } },
            { "patchline": { "destination": [ "obj-237", 0 ], "source": [ "obj-307", 0 ] } },
            { "patchline": { "destination": [ "obj-238", 0 ], "source": [ "obj-308", 0 ] } },
            { "patchline": { "destination": [ "obj-239", 0 ], "source": [ "obj-309", 0 ] } },
            { "patchline": { "destination": [ "obj-240", 0 ], "source": [ "obj-310", 0 ] } },
            { "patchline": { "destination": [ "obj-241", 0 ], "source": [ "obj-311", 0 ] } },
            { "patchline": { "destination": [ "obj-242", 0 ], "source": [ "obj-312", 0 ] } },
            { "patchline": { "destination": [ "obj-243", 0 ], "source": [ "obj-313", 0 ] } },
            { "patchline": { "destination": [ "obj-244", 0 ], "source": [ "obj-314", 0 ] } },
            { "patchline": { "destination": [ "obj-245", 0 ], "source": [ "obj-315", 0 ] } },
            { "patchline": { "destination": [ "obj-246", 0 ], "source": [ "obj-316", 0 ] } },
            { "patchline": { "destination": [ "obj-247", 0 ], "source": [ "obj-317", 0 ] } },
            { "patchline": { "destination": [ "obj-248", 0 ], "source": [ "obj-318", 0 ] } },
            { "patchline": { "destination": [ "obj-249", 0 ], "source": [ "obj-319", 0 ] } },
            { "patchline": { "destination": [ "obj-250", 0 ], "source": [ "obj-320", 0 ] } },
            { "patchline": { "destination": [ "obj-251", 0 ], "source": [ "obj-321", 0 ] } },
            { "patchline": { "destination": [ "obj-252", 0 ], "source": [ "obj-322", 0 ] } },
            { "patchline": { "destination": [ "obj-253", 0 ], "source": [ "obj-323", 0 ] } },
            { "patchline": { "destination": [ "obj-254", 0 ], "source": [ "obj-324", 0 ] } },
            { "patchline": { "destination": [ "obj-255", 0 ], "source": [ "obj-325", 0 ] } },
            { "patchline": { "destination": [ "obj-256", 0 ], "source": [ "obj-326", 0 ] } },
            { "patchline": { "destination": [ "obj-257", 0 ], "source": [ "obj-327", 0 ] } },
            { "patchline": { "destination": [ "obj-258", 0 ], "source": [ "obj-328", 0 ] } },
            { "patchline": { "destination": [ "obj-259", 0 ], "source": [ "obj-329", 0 ] } },
            { "patchline": { "destination": [ "obj-260", 0 ], "source": [ "obj-330", 0 ] } },
            { "patchline": { "destination": [ "obj-261", 0 ], "source": [ "obj-331", 0 ] } },
            { "patchline": { "destination": [ "obj-262", 0 ], "source": [ "obj-332", 0 ] } },
            { "patchline": { "destination": [ "obj-263", 0 ], "source": [ "obj-333", 0 ] } },
            { "patchline": { "destination": [ "obj-264", 0 ], "source": [ "obj-334", 0 ] } },
            { "patchline": { "destination": [ "obj-265", 0 ], "source": [ "obj-335", 0 ] } },
            { "patchline": { "destination": [ "obj-266", 0 ], "source": [ "obj-336", 0 ] } },
            { "patchline": { "destination": [ "obj-267", 0 ], "source": [ "obj-337", 0 ] } },
            { "patchline": { "destination": [ "obj-268", 0 ], "source": [ "obj-338", 0 ] } },
            { "patchline": { "destination": [ "obj-269", 0 ], "source": [ "obj-339", 0 ] } },
            { "patchline": { "destination": [ "obj-270", 0 ], "source": [ "obj-340", 0 ] } },
            { "patchline": { "destination": [ "obj-271", 0 ], "source": [ "obj-341", 0 ] } },
            { "patchline": { "destination": [ "obj-272", 0 ], "source": [ "obj-342", 0 ] } },
            { "patchline": { "destination": [ "obj-273", 0 ], "source": [ "obj-343", 0 ] } },
            { "patchline": { "destination": [ "obj-274", 0 ], "source": [ "obj-344", 0 ] } },
            { "patchline": { "destination": [ "obj-275", 0 ], "source": [ "obj-345", 0 ] } },
            { "patchline": { "destination": [ "obj-276", 0 ], "source": [ "obj-346", 0 ] } },
            { "patchline": { "destination": [ "obj-277", 0 ], "source": [ "obj-347", 0 ] } },
            { "patchline": { "destination": [ "obj-278", 0 ], "source": [ "obj-348", 0 ] } },
            { "patchline": { "destination": [ "obj-279", 0 ], "source": [ "obj-349", 0 ] } },
            { "patchline": { "destination": [ "obj-280", 0 ], "source": [ "obj-350", 0 ] } },
            { "patchline": { "destination": [ "obj-281", 0 ], "source": [ "obj-351", 0 ] } },
            { "patchline": { "destination": [ "obj-282", 0 ], "source": [ "obj-352", 0 ] } },
            { "patchline": { "destination": [ "obj-283", 0 ], "source": [ "obj-353", 0 ] } },
            { "patchline": { "destination": [ "obj-284", 0 ], "source": [ "obj-354", 0 ] } },
            { "patchline": { "destination": [ "obj-285", 0 ], "source": [ "obj-355", 0 ] } }
        ],
        "autosave": 0
    }
}
